### ISSUE TITLE
CI fehlt!

### ISSUE THREAD

**Issue by InnayTool** [foss-ag/vortrag_bramble-briar#1]
Ich bin mir grad nich sicher über den Stand der .travis.toml, was man machen muss, damit das läuft.

**Comment by dragetd** [comment]
Zunächst muss das Repo unter travis-ci.org aktiviert werden. Dazu solltest du auch die Rechte haben weil alles FOSS-AG. Habe ich aber gerade schonmal gemacht.

Was man jetzt noch braucht ist die Config. Ich nutze meist den yml Standard - kannst du dir ja bei den anderen Repos mal abgucken. :)

**Comment by dragetd** [comment]
Nicht notwendig, aber ich finde es immer schön im Hauptordner nur eine .tex Datei zu haben und den Rest unter /inc oder so. Dann weiß man direkt welches Dokument man erstellen muss.

Wenn es dann auch noch wie der Vortrag heißt, ist die default Ausgabe-PDF nicht 'main.pdf'. :)

Ich versuche mal eine Buildconfig zu erstellen.

**Comment by Lazalatin** [comment]
Danke dir! :)

**Comment by dragetd** [comment]
Es fehlte noch eine Env-Variable in der Konfiguration von Travis. Jetzt ist auch der aktuelle Stand da. :)
